apiVersion: v1
kind: Namespace
metadata:
  name: nexora
  labels:
    name: nexora
---
apiVersion: v1
kind: Namespace
metadata:
  name: nexora-monitoring
  labels:
    name: nexora-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: nexora-logging
  labels:
    name: nexora-logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: nexora-database
  labels:
    name: nexora-database
